### ISSUE TITLE
Theme for vaadin-tabs

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-valo-theme#19]
Now that `vaadin-tabs` first alpha is released, a Valo theme for them would be great!

**Comment by manolo** [comment]
you are quick :-), thanks. @jouni should be working on it.

**Comment by heruan** [comment]
Just to have an issue to subscribe to and keep up-to-date! 😄 Thank you!

**Comment by jouni** [comment]
@heruan is probably the most eager and active user we’ve ever had – thanks for the support! 😃 

I have the theme for tabs mostly ready, but because of https://github.com/vaadin/vaadin-tabs/issues/58 it’s not working as expected in IE11 and Edge14.

I could just push the current work to master, and fix the incompatibility later…

**Comment by jouni** [comment]
We’ll wait for the tabs issue to be resolved and fix the theme to work with IE11/Edge14 before making a new release.

**Comment by heruan** [comment]
Of course! The theme is really great, thank you for the commit!

I can use it right away for a couple of demos, giving a better idea of the final look and feel (one of them is a port from Framework 8 to Flow, which used `TabSheet`, hence my eagerness 😉).
