### ISSUE TITLE
Badge on components

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-valo-theme#27]
It would be very useful to have "badges" either standalone or applied to components, to highlight them and possibly provide additional info. Some example from [Bootstrap](https://getbootstrap.com/docs/4.0/components/badge/) and [Material Design Lite](https://getmdl.io/components/#badges-section):

- a badge could be a standalone component (possibly a link/button itself), e.g.

<img width="466" alt="screen shot 2017-11-07 at 12 20 46" src="https://user-images.githubusercontent.com/851745/32491329-9cb4bf7c-c3b6-11e7-82a8-78525df99aa9.png">

- a badge could be placed inside a component, e.g.

<img width="115" alt="screen shot 2017-11-07 at 12 21 14" src="https://user-images.githubusercontent.com/851745/32491429-f0c55fae-c3b6-11e7-8175-a35eb893fbb5.png">
<img width="424" alt="screen shot 2017-11-07 at 12 22 57" src="https://user-images.githubusercontent.com/851745/32491472-1f1953f6-c3b7-11e7-87a5-e3042ecac898.png">

- a badge could be placed around a component, e.g.

<img width="211" alt="screen shot 2017-11-07 at 12 23 48" src="https://user-images.githubusercontent.com/851745/32491447-0204ecf8-c3b7-11e7-81f9-bdb9afa9cbb5.png">
<img width="226" alt="screen shot 2017-11-07 at 12 23 56" src="https://user-images.githubusercontent.com/851745/32491451-0c2582c4-c3b7-11e7-9819-2646ec8825b7.png">

I'm not sure how this should be addressed. Since it could be applied to pretty much all (non-layout) components, should it be a component itself or just a style to be applied as a class?

**Comment by jouni** [comment]
Thanks for the suggestion. Definitely something that has been on the TODO, but not a high priority yet.

IMO a simple `<div theme="badge">` would be suitable (with variations like "badge-primary", "badge-error" and "badge-success"). Those could be imported and included with a separate style module:

```html
<link rel="import" href="vaadin-valo-theme/badge.html">

<custom-style>
  <style include="valo-badge"></style>
</custom-style>

<div theme="badge-primary">Primary</div>
```

**Comment by heruan** [comment]
I came up with this: https://github.com/heruan/vaadin-valo-theme/blob/badge/badge.html

```
$ git clone -b badge https://github.com/heruan/vaadin-valo-theme.git valo-badge
$ cd valo-badge
$ bower install
$ polymer serve --open --open-path components/vaadin-valo-theme/demo/badges.html
```

This started more like an exercise, as it's my first attempt on web components styling, but I'd be happy to know if it meets Valo guidelines.

**Comment by jouni** [comment]
Thanks a lot! Looking pretty good. I do have a few comments, still 🤓

### Include used style modules

In addition to the `typography` module, you should also import the `color` and `sizing-and-spacing` modules (I’ll probably split the sizing-and-spacing into separate modules soon, btw), as you are using custom properties defined in those modules.

### Global property additions

The first `<custom-style>` definition looks unnecessary/wrong. `--valo-space-xxs` is not used anywhere. `--valo-font-size-xxs` should be added to the typography module, not here (but I suppose this was just a prototype). Use `0.75rem` for that (12px usually). `valo-typography` should not be included by default.

The other badge specific custom properties should be defined in the `[theme~="badge"]` selector. Though, I would try to avoid introducing any additional properties if possible. Premature API I would say, and we can add those later if needed. For now I would just stick with using `--valo-font-size-xxs` and `line-height: 1;` directly.

### Text colors

Use the text specific color properties for text `color` – `--valo-primary-text-color` instead of `--valo-primary-color`. This ensures proper accessible contrast in most situations.

### Stylistic choices

These are subjective, of course, but I reserve the right to be the dictator in these matters. I hope you understand 😄
- No shadow
- Font family should be set to `--valo-font-family`
- `text-transform` and `letter-spacing` should be reset to `initial` to be safe that they are not inherited from the parent (such as a button with uppercase text)
- Font weight should be `500` (medium)
- The default font size should be `--valo-font-size-xs`
- Add a `small` variant that uses `--valo-font-size-xxs` and smaller padding (introduce `--valo-space-wide-xxs: 3px 6px;`)
- I would drop the `pill` variant at this point. I haven’t planned that kind of style at least yet.
- The basic style should use the “positive” color palette, and we should have a `filled` variant that uses the “negative” color palette. The basic style should use the translucent colors such as `--valo-contrast-10pct` and `--valo-primary-color-10pct` and corresponding text colors, and the “filled” style should use the opaque colors and the corresponding contrast colors for text.
- An empty badge should be smaller than ones with content (use `--valo-space-m` and `--valo-space-s` for small), always a circle and always use the “negative” color palette.
- When applied to an icon, the size should be 22x22 in size, with 2px padding, resulting in 18x18 icon size (75% of normal). For a small style, remove the padding and set the size to 18x18.
  - The icon sizing is currently fixed, but I have plans to introduce some custom properties for controlling these later on

Here’s a mockup of all the variants that I’ve been planning:
![badges](https://user-images.githubusercontent.com/66382/32606466-10f8fcc4-c55e-11e7-8105-8543e4412b6d.png)

**Comment by jouni** [comment]
The additional positioning variants seem handy. I hadn’t really thought about those yet, but they seem quite alright. Need to test those a bit more to feel comfortable adding them.

**Comment by jouni** [comment]
The name “filled” is not perhaps the best. The other option I’ve been thinking is “contrast”.

**Comment by jouni** [comment]
Also, I’m still not 100% sure we should use the spacing properties for these kinds of situations, and opt to use the sizing properties instead. The spacing properties should more probably be reserved just for white space between components, and not inside a single component.

Data grid cell padding is one exception, where I think spacing properties are natural to use.

**Comment by jouni** [comment]
I’m probably going to introduce `--valo-size-xxs: 22px` and `--valo-size-xxxs: 18px` and we could use those for the badge sizing.

**Comment by jouni** [comment]
In the demo, we should extract the instructions to import & include the “valo-badge” style module to the top of the page. Right now the style module is imported multiple times on the page, resulting in duplicate style declarations.

**Comment by jouni** [comment]
I actually did a quick prototype of the sizing of the badges (excluding icons), and I think this would make more sense than what I tried to formulate in my in the previous comment: http://jsbin.com/fajosekiqo/edit?html,css,output

**Comment by heruan** [comment]
> These are subjective, of course, but I reserve the right to be the dictator in these matters. I hope you understand 😄 

Of course! Those are exactly what I was looking for 😉 

- [x] Include used style modules
- [x] Global property additions
- [x] Text colors
- [x] Stylistic choices

I conformed to all your comments, but I left pills and positioning (fixed a lot on positioning!) in case you might reconsider including them. Otherwise, if you think this branch is worth a PR and you absolutely want them gone for the moment, I'll remove them and keep them safe for a time when humanity will be ready for them 😃 

P.S. I'd rather drop positioning, if I had to choose: it's ~50 lines out of ~100 total and although it fits neat in buttons, I agree it needs to be tested more thoroughly in different scenarios too.

**Comment by jouni** [comment]
@heruan, thanks again for the work!

I think I would be ready to take this in, and possibly do some small modifications myself afterward. Do you want to make a PR, or can I just somehow cherrypick your changes from your fork?

**Comment by Zynde** [comment]
Thanks for the work. This looks like a great addition that I'll certainly use

**Comment by heruan** [comment]
Just issued the PR. I can integrate modifications discussed there, otherwise feel free to make your own afterwards!
