### ISSUE TITLE
Styling links as buttons

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-valo-theme#34]
I guess this is borderline, but it would be very useful to style links as buttons, e.g. to let the use <kbd>CMD</kbd> + click and open a new tab.

How much the templating system can help on applying the `valo-button` theme module to an anchor element, with all variants, without the need to maintain a duplicate style?

**Comment by jouni** [comment]
Yeah, would be useful in some cases. I actually wanted to do this in the theme documentation pages, and ended up prototyping this a bit.

It’s possible but requires pretty much 2x selectors in the valo-button style module, so I’m wondering if that’s an acceptable tradeoff?

The way you would use this:

```html
<link rel="import" href="../vaadin-button.html">

<custom-style>
  <style include="valo-button">
  </style>
</custom-style>

<a href="..." theme="button primary large">Button link</a>
```

Examples of the duplication of selectors used in the style module:

```css
:host,
[theme~="button"]


:host(:hover:not([theme*="tertiary"]):not([active])),
[theme~="button"]:hover:not([theme*="tertiary"]):not([active])


:host::before,
:host::after,
[theme~="button"]::before,
[theme~="button"]::after


:host([active]:not([theme~="primary"]):not([theme*="tertiary"])),
[theme~="button"]:active:not([theme~="primary"]):not([theme*="tertiary"])
```

**Comment by heruan** [comment]
I didn't understand entirely the duplication of selectors, although it seems acceptable to me. The use case is intuitive and clean! 👍

**Comment by jouni** [comment]
Basically, wherever there’s a `:host` selector, we also need to duplicate it and replace `:host` with `[theme~="button"]`, becuase `:host` won’t match anything outside a custom element.

The `[active]` state needs to be changed to `:active` as well.

**Comment by heruan** [comment]
@jouni  Now that the button theme is moved to the button repository, where's the best location to include this (if you're okay to proceed with it, of course!)?

**Comment by jouni** [comment]
This repo would still be the logical place for the styles. `vaadin-button` would then just include the style modules from this package.

I still don’t exactly know how to pull this off nicely. My previous suggestions doesn’t really work, as the `:host` selectors can end up matching unwanted elements (when you import&include the style module in another custom element).

The only other option I now see is to have some build script that generates a `vaadin-button` specific style module from a more generic module. Since there’s one other case that needs a build script (https://github.com/vaadin/vaadin-valo-styles/blob/master/color.html#L190), it might be okay to introduce a build step for this package.

**Comment by jouni** [comment]
This issue was moved to vaadin/vaadin-lumo-styles#5
